USE [SharedServices]
GO

DELETE FROM UNST_ZNST_Staging;
GO

ALTER TABLE UNST_ZNST_Staging
ADD INSERT_DATE datetime NOT NULL;
GO

ALTER TABLE [dbo].[UNST_ZNST_Staging] ADD  CONSTRAINT [DF_UNST_ZNST_Staging_INSERT_DATE]  DEFAULT (getdate()) FOR [INSERT_DATE]
GO