USE [SharedServices]
GO

DELETE FROM [dbo].[UNST_ZNST_Staging]

GO

ALTER TABLE [dbo].[UNST_ZNST_Staging]
	ADD ACCOUNT VARCHAR(50) NOT NULL;
GO

ALTER TABLE [dbo].[UNST_ZNST]
	DROP CONSTRAINT PK_UNST_ZNST;
GO

ALTER TABLE [dbo].[UNST_ZNST]
	ADD CONSTRAINT [PK_UNST_ZNST] PRIMARY KEY CLUSTERED 
(
	[ACCOUNT] ASC,
	[INVOICE_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO