USE [SharedServices]
GO

CREATE VIEW [dbo].[UNST_ZNST-Pending]
AS
SELECT        WHSE, ACCOUNT, CUST, NAME, ORIG_BAL, BAL, INVOICE_NUM, DATE, PROCESS_DATE, WRITER, AR_GL_NUM, ORDCDE, SELL_WHSE, SHIP_WHSE, JOB, SRM, CRED_MGR, CRMEMO, SHIP_INSTR1, SHIP_INSTR2, 
                         SHIP_INSTR3, SHIP_INSTR4, OML_ASSOC, CUST_PO, OML_ASSOC_MAIL, OML_SUPER_NAME, OML_SUPER_MAIL, PY_TYPE, PY_NUMBER, PY_COMMENT, PY_AMOUNT, PY_DATE, PY_EMPLOYEE_NAME, CM_STATUS, 
                         INSERT_DATE, CHECKED_OUT, OWNER, STATUS, PENDING, START_DATE, UPDATE_DATE, END_DATE
FROM            dbo.UNST_ZNST
WHERE        (PENDING = 1) AND (CHECKED_OUT = 0)

GO