USE [SharedServices]
GO

CREATE VIEW [dbo].[DWFEI_COMB_WHSE_DIM]
AS
SELECT        WAREHOUSE_NUMBER_NK, ACCOUNT_NUMBER_NK, ALIAS_NAME, ACCOUNT_NAME, WAREHOUSE_NAME, WHSE_STATUS, KIND_OF_BUSINESS, DISTRICT, REGION_NAME, BUSINESS_UNIT, BU_NAME, BU2_NAME, 
                         LEVEL8, LEVEL9, LEVEL10, RPC
FROM            OPENQUERY([DWFEI.HQ.FERG.COM], '
SELECT * FROM DW_FEI.COMB_WHSE_DIMENSION
') AS derivedtbl_1

GO
