USE [SharedServices]
GO

/****** Object:  Index [IX_POA_ACCOUNT]    Script Date: 3/20/2018 3:31:07 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_ACCOUNT] ON [dbo].[POA_ZOAP]
(
	[ACCOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_ARGLNUM]    Script Date: 3/20/2018 3:31:17 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_ARGLNUM] ON [dbo].[POA_ZOAP]
(
	[AR_GL_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_CHECKEDOUT]    Script Date: 3/20/2018 3:31:26 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_CHECKEDOUT] ON [dbo].[POA_ZOAP]
(
	[CHECKED_OUT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_DATE]    Script Date: 3/20/2018 3:31:43 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_DATE] ON [dbo].[POA_ZOAP]
(
	[DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_END_DATE]    Script Date: 3/20/2018 3:38:35 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_END_DATE] ON [dbo].[POA_ZOAP]
(
	[END_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_FUTPASTFLG]    Script Date: 3/20/2018 3:38:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_FUTPASTFLG] ON [dbo].[POA_ZOAP]
(
	[FUT PAST FLG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_INSERT_DATE]    Script Date: 3/20/2018 3:38:59 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_INSERT_DATE] ON [dbo].[POA_ZOAP]
(
	[INSERT_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_OWNER]    Script Date: 3/20/2018 3:39:09 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_OWNER] ON [dbo].[POA_ZOAP]
(
	[OWNER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_PENDING]    Script Date: 3/20/2018 3:40:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_PENDING] ON [dbo].[POA_ZOAP]
(
	[PENDING] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_START_DATE]    Script Date: 3/20/2018 3:40:56 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_START_DATE] ON [dbo].[POA_ZOAP]
(
	[START_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_STATUS]    Script Date: 3/20/2018 3:41:05 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_STATUS] ON [dbo].[POA_ZOAP]
(
	[STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_UPDATE_DATE]    Script Date: 3/20/2018 3:41:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_UPDATE_DATE] ON [dbo].[POA_ZOAP]
(
	[UPDATE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_PendingLog-OwnerID]    Script Date: 3/20/2018 3:43:46 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_PendingLog-OwnerID] ON [dbo].[POA_PendingLog]
(
	[OwnerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_PendingLog-TrilAcctName]    Script Date: 3/20/2018 3:43:53 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_PendingLog-TrilAcctName] ON [dbo].[POA_PendingLog]
(
	[TrilAcctName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_MemoLog-DATETIME]    Script Date: 3/20/2018 3:44:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_MemoLog-DATETIME] ON [dbo].[POA_MemoLog]
(
	[MemoDateTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_MemoLog-USERID]    Script Date: 3/20/2018 3:44:21 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_MemoLog-USERID] ON [dbo].[POA_MemoLog]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_BranchAccountInfo-TrilAcctName]    Script Date: 3/20/2018 3:46:26 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_BranchAccountInfo-TrilAcctName] ON [dbo].[POA_BranchAccountInfo]
(
	[TrilogieAcctName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_BranchAccountInfo-CloseDate]    Script Date: 3/20/2018 3:46:36 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_BranchAccountInfo-CloseDate] ON [dbo].[POA_BranchAccountInfo]
(
	[CloseDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_Associates-FullName]    Script Date: 3/20/2018 3:46:57 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_Associates-FullName] ON [dbo].[POA_Associates]
(
	[FullName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_Associates-Initials]    Script Date: 3/20/2018 3:47:04 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_Associates-Initials] ON [dbo].[POA_Associates]
(
	[Initials] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_POA_Associates-JobTitle]    Script Date: 3/20/2018 3:47:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_POA_Associates-JobTitle] ON [dbo].[POA_Associates]
(
	[JobTitle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-Date]    Script Date: 3/20/2018 3:47:50 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_CalendarDim-Date] ON [dbo].[CalendarDim]
(
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-MonthYear]    Script Date: 3/20/2018 3:48:21 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-MonthYear] ON [dbo].[CalendarDim]
(
	[MonthYear] ASC,
	[MMYYYY] ASC,
	[FiscalMMYYYY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-Year]    Script Date: 3/20/2018 3:48:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-Year] ON [dbo].[CalendarDim]
(
	[Year] ASC,
	[FiscalYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-Quarter]    Script Date: 3/20/2018 3:49:04 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-Quarter] ON [dbo].[CalendarDim]
(
	[Quarter] ASC,
	[FiscalQuarter] ASC,
	[QuarterName] ASC,
	[FiscalQuarterName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-Month]    Script Date: 3/20/2018 3:49:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-Month] ON [dbo].[CalendarDim]
(
	[Month] ASC,
	[FiscalMonth] ASC,
	[MonthName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-WeekOfYear]    Script Date: 3/20/2018 3:49:21 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-WeekOfYear] ON [dbo].[CalendarDim]
(
	[WeekOfYear] ASC,
	[FiscalWeekOfYear] ASC,
	[ISOWeekOfYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-DayOfYear]    Script Date: 3/20/2018 3:49:29 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-DayOfYear] ON [dbo].[CalendarDim]
(
	[DayOfYear] ASC,
	[DayOfFiscalYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-DOWInMonth]    Script Date: 3/20/2018 3:49:41 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-DOWInMonth] ON [dbo].[CalendarDim]
(
	[DOWInMonth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-Holiday]    Script Date: 3/20/2018 3:52:09 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-Holiday] ON [dbo].[CalendarDim]
(
	[IsHoliday] ASC,
	[HolidayText] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-Weekend]    Script Date: 3/20/2018 3:52:18 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-Weekend] ON [dbo].[CalendarDim]
(
	[IsWeekend] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-Weekday]    Script Date: 3/20/2018 3:52:26 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-Weekday] ON [dbo].[CalendarDim]
(
	[Weekday] ASC,
	[WeekDayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


/****** Object:  Index [IX_CalendarDim-Day]    Script Date: 3/20/2018 3:52:45 PM ******/
CREATE NONCLUSTERED INDEX [IX_CalendarDim-Day] ON [dbo].[CalendarDim]
(
	[Day] ASC,
	[BusinessDayOfMonth] ASC,
	[DaySuffix] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

