--UPDATE [dbo].[POA_ZOAP] SET POA_ZOAP.[AR BAL NC] = POA_ZOAP_Staging.[AR BAL NC], POA_ZOAP.[POA BAL] = POA_ZOAP_Staging.[POA BAL]
SELECT POA_ZOAP.[AR BAL NC], POA_ZOAP.[POA BAL], POA_ZOAP.[STATUS]
FROM POA_ZOAP INNER JOIN POA_ZOAP_Staging ON POA_ZOAP.INVOICE = POA_ZOAP_Staging.INVOICE
WHERE POA_ZOAP.Status <> 'Partial'